version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: plant-iot-postgres
    environment:
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    image: plant-iot-backend-backend:latest
    container_name: plant-iot-backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]