name: plant_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  go_router: ^17.3.0
  fl_chart: ^1.2.0
  dio: ^5.10.0
  shared_preferences: ^2.3.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  glados: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/fake_sensor_data.json
